Update OU delete with ou tree and data
It no longer works in newer databases
ERROR:  relation "trackedentitydatavalue" does not exist
LINE 1: DELETE FROM trackedentitydatavalue WHERE programstageinstanc...
                    ^
QUERY:  DELETE FROM trackedentitydatavalue WHERE programstageinstanceid IN (SELECT programstageinstanceid FROM programstageinstance WHERE organisationunitid = $1 OR programinstanceid IN (SELECT programinstanceid FROM programinstance WHERE organisationunitid = $1 OR trackedentityinstanceid IN (SELECT trackedentityinstanceid FROM trackedentityinstance WHERE organisationunitid = $1)))
CONTEXT:  PL/pgSQL function delete_orgunittree_with_data(character) line 26 at EXECUTE

This table does not exist anymore either organisationunittranslations

Possible fix proposed